Name: Victorem
IconPath: MyTeam.png
SoundPath: MyTeam.wav
Description: |
    L'équipe d'Alexandre Culty et Vincent Iampietro.
BrainsPackage: myteam
AgentsBrainClasses:
    WarBase: WarBaseBrainController
    WarExplorer: WarExplorerBrainController
    WarLight: WarLightBrainController
    WarHeavy: WarHeavyBrainController
    WarRocketLauncher: WarRocketLauncherBrainController
    WarKamikaze: WarKamikazeBrainController
    WarEngineer: WarEngineerBrainController
    WarTurret: WarTurretBrainController
